/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_defcfg = 4,
  anon_sym_defsrc = 5,
  anon_sym_deflayer = 6,
  anon_sym_deflayermap = 7,
  anon_sym_defalias = 8,
  anon_sym_defaliasenvcond = 9,
  anon_sym_defvar = 10,
  anon_sym_deftemplate = 11,
  anon_sym_defseq = 12,
  anon_sym_defoverrides = 13,
  anon_sym_deffakekeys = 14,
  anon_sym_defvirtualkeys = 15,
  anon_sym_defchords = 16,
  anon_sym_defzippy = 17,
  anon_sym_defzippy_DASHexperimental = 18,
  anon_sym_deflocalkeys_DASHwin = 19,
  anon_sym_deflocalkeys_DASHwiniov2 = 20,
  anon_sym_deflocalkeys_DASHwintercept = 21,
  anon_sym_deflocalkeys_DASHlinux = 22,
  anon_sym_deflocalkeys_DASHmacos = 23,
  sym_number = 24,
  sym_variable = 25,
  sym_alias = 26,
  sym_string = 27,
  sym_line_comment = 28,
  sym_block_comment = 29,
  sym_source_file = 30,
  sym_sexpr = 31,
  sym_list = 32,
  sym_keyword = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_list_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_defcfg] = "defcfg",
  [anon_sym_defsrc] = "defsrc",
  [anon_sym_deflayer] = "deflayer",
  [anon_sym_deflayermap] = "deflayermap",
  [anon_sym_defalias] = "defalias",
  [anon_sym_defaliasenvcond] = "defaliasenvcond",
  [anon_sym_defvar] = "defvar",
  [anon_sym_deftemplate] = "deftemplate",
  [anon_sym_defseq] = "defseq",
  [anon_sym_defoverrides] = "defoverrides",
  [anon_sym_deffakekeys] = "deffakekeys",
  [anon_sym_defvirtualkeys] = "defvirtualkeys",
  [anon_sym_defchords] = "defchords",
  [anon_sym_defzippy] = "defzippy",
  [anon_sym_defzippy_DASHexperimental] = "defzippy-experimental",
  [anon_sym_deflocalkeys_DASHwin] = "deflocalkeys-win",
  [anon_sym_deflocalkeys_DASHwiniov2] = "deflocalkeys-winiov2",
  [anon_sym_deflocalkeys_DASHwintercept] = "deflocalkeys-wintercept",
  [anon_sym_deflocalkeys_DASHlinux] = "deflocalkeys-linux",
  [anon_sym_deflocalkeys_DASHmacos] = "deflocalkeys-macos",
  [sym_number] = "number",
  [sym_variable] = "variable",
  [sym_alias] = "alias",
  [sym_string] = "string",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_sexpr] = "sexpr",
  [sym_list] = "list",
  [sym_keyword] = "keyword",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_defcfg] = anon_sym_defcfg,
  [anon_sym_defsrc] = anon_sym_defsrc,
  [anon_sym_deflayer] = anon_sym_deflayer,
  [anon_sym_deflayermap] = anon_sym_deflayermap,
  [anon_sym_defalias] = anon_sym_defalias,
  [anon_sym_defaliasenvcond] = anon_sym_defaliasenvcond,
  [anon_sym_defvar] = anon_sym_defvar,
  [anon_sym_deftemplate] = anon_sym_deftemplate,
  [anon_sym_defseq] = anon_sym_defseq,
  [anon_sym_defoverrides] = anon_sym_defoverrides,
  [anon_sym_deffakekeys] = anon_sym_deffakekeys,
  [anon_sym_defvirtualkeys] = anon_sym_defvirtualkeys,
  [anon_sym_defchords] = anon_sym_defchords,
  [anon_sym_defzippy] = anon_sym_defzippy,
  [anon_sym_defzippy_DASHexperimental] = anon_sym_defzippy_DASHexperimental,
  [anon_sym_deflocalkeys_DASHwin] = anon_sym_deflocalkeys_DASHwin,
  [anon_sym_deflocalkeys_DASHwiniov2] = anon_sym_deflocalkeys_DASHwiniov2,
  [anon_sym_deflocalkeys_DASHwintercept] = anon_sym_deflocalkeys_DASHwintercept,
  [anon_sym_deflocalkeys_DASHlinux] = anon_sym_deflocalkeys_DASHlinux,
  [anon_sym_deflocalkeys_DASHmacos] = anon_sym_deflocalkeys_DASHmacos,
  [sym_number] = sym_number,
  [sym_variable] = sym_variable,
  [sym_alias] = sym_alias,
  [sym_string] = sym_string,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_sexpr] = sym_sexpr,
  [sym_list] = sym_list,
  [sym_keyword] = sym_keyword,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defcfg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defsrc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deflayer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deflayermap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defalias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defaliasenvcond] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defvar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deftemplate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defseq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defoverrides] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deffakekeys] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defvirtualkeys] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defchords] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defzippy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defzippy_DASHexperimental] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deflocalkeys_DASHwin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deflocalkeys_DASHwiniov2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deflocalkeys_DASHwintercept] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deflocalkeys_DASHlinux] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deflocalkeys_DASHmacos] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_sexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 11,
  [16] = 12,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(114);
      ADVANCE_MAP(
        '"', 2,
        '#', 268,
        '$', 273,
        '(', 115,
        ')', 116,
        '-', 271,
        ';', 164,
        '@', 274,
        'd', 184,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(157);
      if (lookahead != 0) ADVANCE(275);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 268,
        '$', 273,
        '(', 115,
        ')', 116,
        '-', 271,
        ';', 164,
        '@', 274,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(157);
      if (lookahead != 0) ADVANCE(275);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(276);
      if (lookahead == '\\') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(278);
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(111);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(58);
      END_STATE();
    case 5:
      if (lookahead == '2') ADVANCE(149);
      END_STATE();
    case 6:
      if (lookahead == ';') ADVANCE(277);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        'a', 56,
        'c', 43,
        'f', 8,
        'l', 9,
        'o', 101,
        's', 27,
        't', 28,
        'v', 10,
        'z', 45,
      );
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(109);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(79);
      if (lookahead == 'i') ADVANCE(80);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(87);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(97);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(55);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(60);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(119);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(68);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(71);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(127);
      END_STATE();
    case 24:
      if (lookahead == 'd') ADVANCE(88);
      END_STATE();
    case 25:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(131);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(106);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 42:
      if (lookahead == 'f') ADVANCE(7);
      END_STATE();
    case 43:
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 'h') ADVANCE(70);
      END_STATE();
    case 44:
      if (lookahead == 'g') ADVANCE(117);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(63);
      END_STATE();
    case 51:
      if (lookahead == 'k') ADVANCE(39);
      END_STATE();
    case 52:
      if (lookahead == 'k') ADVANCE(31);
      END_STATE();
    case 53:
      if (lookahead == 'k') ADVANCE(40);
      END_STATE();
    case 54:
      if (lookahead == 'k') ADVANCE(41);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(145);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 58:
      if (lookahead == 'l') ADVANCE(49);
      if (lookahead == 'm') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(50);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 60:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 61:
      if (lookahead == 'm') ADVANCE(74);
      END_STATE();
    case 62:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(148);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(102);
      END_STATE();
    case 65:
      if (lookahead == 'n') ADVANCE(98);
      END_STATE();
    case 66:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 67:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(67);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(100);
      END_STATE();
    case 70:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(93);
      END_STATE();
    case 72:
      if (lookahead == 'p') ADVANCE(123);
      END_STATE();
    case 73:
      if (lookahead == 'p') ADVANCE(105);
      END_STATE();
    case 74:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 75:
      if (lookahead == 'p') ADVANCE(73);
      END_STATE();
    case 76:
      if (lookahead == 'p') ADVANCE(95);
      END_STATE();
    case 77:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 78:
      if (lookahead == 'q') ADVANCE(133);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(129);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(94);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 82:
      if (lookahead == 'r') ADVANCE(122);
      END_STATE();
    case 83:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 84:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 85:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 86:
      if (lookahead == 'r') ADVANCE(83);
      END_STATE();
    case 87:
      if (lookahead == 's') ADVANCE(126);
      END_STATE();
    case 88:
      if (lookahead == 's') ADVANCE(141);
      END_STATE();
    case 89:
      if (lookahead == 's') ADVANCE(137);
      END_STATE();
    case 90:
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 91:
      if (lookahead == 's') ADVANCE(135);
      END_STATE();
    case 92:
      if (lookahead == 's') ADVANCE(139);
      END_STATE();
    case 93:
      if (lookahead == 's') ADVANCE(155);
      END_STATE();
    case 94:
      if (lookahead == 't') ADVANCE(99);
      END_STATE();
    case 95:
      if (lookahead == 't') ADVANCE(151);
      END_STATE();
    case 96:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 97:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 98:
      if (lookahead == 'u') ADVANCE(103);
      END_STATE();
    case 99:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 100:
      if (lookahead == 'v') ADVANCE(5);
      END_STATE();
    case 101:
      if (lookahead == 'v') ADVANCE(32);
      END_STATE();
    case 102:
      if (lookahead == 'v') ADVANCE(19);
      END_STATE();
    case 103:
      if (lookahead == 'x') ADVANCE(153);
      END_STATE();
    case 104:
      if (lookahead == 'x') ADVANCE(77);
      END_STATE();
    case 105:
      if (lookahead == 'y') ADVANCE(144);
      END_STATE();
    case 106:
      if (lookahead == 'y') ADVANCE(89);
      END_STATE();
    case 107:
      if (lookahead == 'y') ADVANCE(90);
      END_STATE();
    case 108:
      if (lookahead == 'y') ADVANCE(92);
      END_STATE();
    case 109:
      if (lookahead == 'y') ADVANCE(33);
      END_STATE();
    case 110:
      if (lookahead == '|') ADVANCE(111);
      END_STATE();
    case 111:
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(111);
      END_STATE();
    case 112:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 113:
      if (eof) ADVANCE(114);
      if (lookahead == '#') ADVANCE(110);
      if (lookahead == '(') ADVANCE(115);
      if (lookahead == ';') ADVANCE(6);
      if (lookahead == 'd') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_defcfg);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_defcfg);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_defsrc);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_defsrc);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_deflayer);
      if (lookahead == 'm') ADVANCE(174);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_deflayer);
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_deflayermap);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_deflayermap);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_defalias);
      if (lookahead == 'e') ADVANCE(222);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_defalias);
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_defaliasenvcond);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_defaliasenvcond);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_defvar);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_defvar);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_deftemplate);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_deftemplate);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_defseq);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_defseq);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_defoverrides);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_defoverrides);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_deffakekeys);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_deffakekeys);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_defvirtualkeys);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_defvirtualkeys);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_defchords);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_defchords);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_defzippy);
      if (lookahead == '-') ADVANCE(187);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_defzippy);
      if (lookahead == '-') ADVANCE(29);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_defzippy_DASHexperimental);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_defzippy_DASHexperimental);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHwin);
      if (lookahead == 'i') ADVANCE(227);
      if (lookahead == 't') ADVANCE(196);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHwin);
      if (lookahead == 'i') ADVANCE(69);
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHwiniov2);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHwiniov2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHwintercept);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHwintercept);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHlinux);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHlinux);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHmacos);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_deflocalkeys_DASHmacos);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(157);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(158);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(159);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_alias);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(160);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#') ADVANCE(269);
      if (lookahead == '|') ADVANCE(161);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')') ADVANCE(111);
      if (lookahead != 0) ADVANCE(269);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(216);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(150);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ';') ADVANCE(270);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'a', 214,
        'c', 201,
        'f', 166,
        'l', 167,
        'o', 259,
        's', 185,
        't', 186,
        'v', 168,
        'z', 203,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(209);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(267);
      if (lookahead == 'o') ADVANCE(178);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(237);
      if (lookahead == 'i') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(245);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(217);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(255);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(213);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(179);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(230);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(218);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(120);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(226);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(170);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(229);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(194);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(128);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(246);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(192);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(200);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(236);
      if (lookahead == 'r') ADVANCE(176);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(219);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(262);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(132);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(264);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(244);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(240);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(249);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(224);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(234);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(243);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(242);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(210);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(265);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(266);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(165);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(202);
      if (lookahead == 'h') ADVANCE(228);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(118);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(233);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(169);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(220);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(183);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(223);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(221);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(197);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(189);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(198);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(199);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(146);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(204);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(171);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(207);
      if (lookahead == 'm') ADVANCE(173);
      if (lookahead == 'w') ADVANCE(208);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(211);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(212);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(232);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(193);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(147);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(260);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(256);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(254);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(181);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(225);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(258);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(239);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(251);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(124);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(263);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(215);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(231);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(253);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(195);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'q') ADVANCE(134);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(130);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(252);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(182);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(121);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(206);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(180);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(205);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(241);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(125);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(142);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(138);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(162);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(136);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(140);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(156);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(257);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(152);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(172);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(188);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(261);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(175);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 258:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(163);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 259:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(190);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 260:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(177);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 261:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(154);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 262:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(235);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 263:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(143);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 264:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(247);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 265:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(248);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 266:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(250);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 267:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(191);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 268:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '|') ADVANCE(269);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '|') ADVANCE(161);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')') ADVANCE(111);
      if (lookahead != 0) ADVANCE(269);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')') ADVANCE(277);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(270);
      END_STATE();
    case 271:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(157);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 272:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(158);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 273:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(159);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 274:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(160);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 275:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(275);
      END_STATE();
    case 276:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 277:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(277);
      END_STATE();
    case 278:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(111);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 113},
  [2] = {.lex_state = 113},
  [3] = {.lex_state = 113},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 113},
  [14] = {.lex_state = 113},
  [15] = {.lex_state = 113},
  [16] = {.lex_state = 113},
  [17] = {.lex_state = 113},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_defcfg] = ACTIONS(1),
    [anon_sym_defsrc] = ACTIONS(1),
    [anon_sym_deflayer] = ACTIONS(1),
    [anon_sym_deflayermap] = ACTIONS(1),
    [anon_sym_defalias] = ACTIONS(1),
    [anon_sym_defaliasenvcond] = ACTIONS(1),
    [anon_sym_defvar] = ACTIONS(1),
    [anon_sym_deftemplate] = ACTIONS(1),
    [anon_sym_defseq] = ACTIONS(1),
    [anon_sym_defoverrides] = ACTIONS(1),
    [anon_sym_deffakekeys] = ACTIONS(1),
    [anon_sym_defvirtualkeys] = ACTIONS(1),
    [anon_sym_defchords] = ACTIONS(1),
    [anon_sym_defzippy] = ACTIONS(1),
    [anon_sym_defzippy_DASHexperimental] = ACTIONS(1),
    [anon_sym_deflocalkeys_DASHwin] = ACTIONS(1),
    [anon_sym_deflocalkeys_DASHwiniov2] = ACTIONS(1),
    [anon_sym_deflocalkeys_DASHwintercept] = ACTIONS(1),
    [anon_sym_deflocalkeys_DASHlinux] = ACTIONS(1),
    [anon_sym_deflocalkeys_DASHmacos] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_alias] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym_list] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(9),
    [sym_block_comment] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_keyword] = STATE(4),
    [anon_sym_defcfg] = ACTIONS(11),
    [anon_sym_defsrc] = ACTIONS(11),
    [anon_sym_deflayer] = ACTIONS(13),
    [anon_sym_deflayermap] = ACTIONS(11),
    [anon_sym_defalias] = ACTIONS(13),
    [anon_sym_defaliasenvcond] = ACTIONS(11),
    [anon_sym_defvar] = ACTIONS(11),
    [anon_sym_deftemplate] = ACTIONS(11),
    [anon_sym_defseq] = ACTIONS(11),
    [anon_sym_defoverrides] = ACTIONS(11),
    [anon_sym_deffakekeys] = ACTIONS(11),
    [anon_sym_defvirtualkeys] = ACTIONS(11),
    [anon_sym_defchords] = ACTIONS(11),
    [anon_sym_defzippy] = ACTIONS(13),
    [anon_sym_defzippy_DASHexperimental] = ACTIONS(11),
    [anon_sym_deflocalkeys_DASHwin] = ACTIONS(13),
    [anon_sym_deflocalkeys_DASHwiniov2] = ACTIONS(11),
    [anon_sym_deflocalkeys_DASHwintercept] = ACTIONS(11),
    [anon_sym_deflocalkeys_DASHlinux] = ACTIONS(11),
    [anon_sym_deflocalkeys_DASHmacos] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(9),
    [sym_block_comment] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_keyword] = STATE(7),
    [anon_sym_defcfg] = ACTIONS(11),
    [anon_sym_defsrc] = ACTIONS(11),
    [anon_sym_deflayer] = ACTIONS(13),
    [anon_sym_deflayermap] = ACTIONS(11),
    [anon_sym_defalias] = ACTIONS(13),
    [anon_sym_defaliasenvcond] = ACTIONS(11),
    [anon_sym_defvar] = ACTIONS(11),
    [anon_sym_deftemplate] = ACTIONS(11),
    [anon_sym_defseq] = ACTIONS(11),
    [anon_sym_defoverrides] = ACTIONS(11),
    [anon_sym_deffakekeys] = ACTIONS(11),
    [anon_sym_defvirtualkeys] = ACTIONS(11),
    [anon_sym_defchords] = ACTIONS(11),
    [anon_sym_defzippy] = ACTIONS(13),
    [anon_sym_defzippy_DASHexperimental] = ACTIONS(11),
    [anon_sym_deflocalkeys_DASHwin] = ACTIONS(13),
    [anon_sym_deflocalkeys_DASHwiniov2] = ACTIONS(11),
    [anon_sym_deflocalkeys_DASHwintercept] = ACTIONS(11),
    [anon_sym_deflocalkeys_DASHlinux] = ACTIONS(11),
    [anon_sym_deflocalkeys_DASHmacos] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(9),
    [sym_block_comment] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 1,
      sym_string,
    STATE(10), 1,
      sym_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(5), 2,
      sym_sexpr,
      aux_sym_list_repeat1,
    ACTIONS(15), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [27] = 7,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      sym_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_sexpr,
      aux_sym_list_repeat1,
    ACTIONS(15), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [54] = 7,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(33), 1,
      sym_string,
    STATE(10), 1,
      sym_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_sexpr,
      aux_sym_list_repeat1,
    ACTIONS(25), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [81] = 7,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(36), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      sym_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(8), 2,
      sym_sexpr,
      aux_sym_list_repeat1,
    ACTIONS(15), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [108] = 7,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(38), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      sym_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_sexpr,
      aux_sym_list_repeat1,
    ACTIONS(15), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [135] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(42), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(40), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [151] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(46), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(44), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [167] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(50), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(48), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [183] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(54), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(52), 4,
      sym_number,
      sym_variable,
      sym_alias,
      sym_identifier,
  [199] = 4,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(14), 2,
      sym_list,
      aux_sym_source_file_repeat1,
  [214] = 4,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(14), 2,
      sym_list,
      aux_sym_source_file_repeat1,
  [229] = 2,
    ACTIONS(9), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [238] = 2,
    ACTIONS(9), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [247] = 2,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 27,
  [SMALL_STATE(6)] = 54,
  [SMALL_STATE(7)] = 81,
  [SMALL_STATE(8)] = 108,
  [SMALL_STATE(9)] = 135,
  [SMALL_STATE(10)] = 151,
  [SMALL_STATE(11)] = 167,
  [SMALL_STATE(12)] = 183,
  [SMALL_STATE(13)] = 199,
  [SMALL_STATE(14)] = 214,
  [SMALL_STATE(15)] = 229,
  [SMALL_STATE(16)] = 238,
  [SMALL_STATE(17)] = 247,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexpr, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexpr, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [63] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kanata(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "kanata",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
